// Draws every app icon from the app's one icon, assets/images/logo.svg:
//
//   * the .exe's icon, windows/runner/resources/app_icon.ico (git-ignored);
//   * Android's launcher icon (legacy PNGs for Android 7, an adaptive icon for
//     8+) and the white status-bar silhouette notifications use, under
//     android/app/src/main/res/.
//
// Run by scripts/build_windows.ps1 and scripts/build_android.ps1 before every
// build, and by the "Generate app icon" VS Code task:
//
//     flutter test tool/generate_app_icon.dart
//
// It is a "test" only because rendering an SVG needs Flutter's own painting
// engine, and `flutter test` is the way to run Dart code with it outside an
// app. Replacing logo.svg and running it again redraws all of them.
import 'dart:convert';
import 'dart:io';
import 'dart:ui' show Color;

import 'package:dhikr_reminder/core/window/svg_icon.dart';
import 'package:flutter_test/flutter_test.dart';

const _windowsOutput = 'windows/runner/resources/app_icon.ico';
const _androidRes = 'android/app/src/main/res';

/// The launcher background, a dark brown that matches the app's gold-on-dark
/// look; the logo sits on it.
const _iconBackground = Color(0xFF1B140B);

/// Launcher icon size per density (48dp).
const _launcherSizes = {
  'mdpi': 48,
  'hdpi': 72,
  'xhdpi': 96,
  'xxhdpi': 144,
  'xxxhdpi': 192,
};

/// Adaptive icon layer size per density (108dp).
const _adaptiveSizes = {
  'mdpi': 108,
  'hdpi': 162,
  'xhdpi': 216,
  'xxhdpi': 324,
  'xxxhdpi': 432,
};

/// Status-bar icon size per density (24dp).
const _notificationSizes = {
  'mdpi': 24,
  'hdpi': 36,
  'xhdpi': 48,
  'xxhdpi': 72,
  'xxxhdpi': 96,
};

/// An adaptive icon shows only the middle 66dp of its 108dp layer: the logo is
/// drawn inside that, so no mask shape can cut it.
const _adaptiveInset = (1 - 66 / 108) / 2;

Future<void> _write(String path, List<int> bytes) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes, flush: true);
}

Future<void> _writeText(String path, String text) =>
    _write(path, utf8.encode(text));

void main() {
  testWidgets('generate the app icons from the SVG', (tester) async {
    await tester.runAsync(() async {
      final svg = await File(kAppIconSvgAsset).readAsString();

      // Windows.
      await _write(_windowsOutput, await renderSvgAsIco(svg));

      // Android: legacy launcher icons (Android 7 and older).
      for (final entry in _launcherSizes.entries) {
        await _write(
          '$_androidRes/mipmap-${entry.key}/ic_launcher.png',
          await renderSvgAsPng(
            svg,
            entry.value,
            inset: 0.1,
            background: _iconBackground,
          ),
        );
      }

      // Android: adaptive icon (8+), foreground per density + the XML.
      for (final entry in _adaptiveSizes.entries) {
        await _write(
          '$_androidRes/mipmap-${entry.key}/ic_launcher_foreground.png',
          await renderSvgAsPng(svg, entry.value, inset: _adaptiveInset),
        );
      }
      await _writeText(
        '$_androidRes/values/ic_launcher_background.xml',
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/generate_app_icon.dart. -->\n'
        '<resources>\n'
        '    <color name="ic_launcher_background">#1B140B</color>\n'
        '</resources>\n',
      );
      await _writeText(
        '$_androidRes/mipmap-anydpi-v26/ic_launcher.xml',
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/generate_app_icon.dart. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background"/>\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>\n'
        '</adaptive-icon>\n',
      );

      // Android: the small white icon notifications show in the status bar.
      for (final entry in _notificationSizes.entries) {
        await _write(
          '$_androidRes/drawable-${entry.key}/ic_notification.png',
          await renderSvgAsPng(svg, entry.value, inset: 0.08, silhouette: true),
        );
      }
    });

    expect(File(_windowsOutput).existsSync(), isTrue);
    expect(
      File('$_androidRes/mipmap-anydpi-v26/ic_launcher.xml').existsSync(),
      isTrue,
    );
  });
}
